x=int(input("enter the valur of x : "))
print(x)
y=int(input("enter the value of y: "))
print(y)
print("arthematic operators")
print("sum of values %d and %d is="%(x,y),x+y)
print ("difference of the values %d and %d is ="%(x,y),x-y)
print("product of the values %d and %d is="%(x,y),x*y)
print("division of the values %d and %d is="%(x,y),x/y)
print("floor division of the values %d and %d is ="%(x,y),x//y)
print("%d to the power of %d is="%(x,y),x**y)
